---
detectors:
  Attribute:
    enabled: false
  FeatureEnvy:
    enabled: false
  IrresponsibleModule:
    enabled: false
  MissingSafeMethod:
    enabled: false
  NilCheck:
    enabled: false
  TooManyInstanceVariables:
    enabled: false
  TooManyStatements:
    max_statements: 10
    exclude:
      - 'GrapeThrottler::Middleware::ThrottleMiddleware#before'
  UncommunicativeVariableName:
    accept:
      - '/^.$/'
      - '/[0-9]$/'
  UtilityFunction:
    enabled: false
