sudo: false
language: ruby
cache: bundler
rvm:
- 2.5
- 2.6
- ruby-head
matrix:
  fast_finish: true
  allow_failures:
  - rvm: ruby-head
before_install:
- gem update --system
- gem install bundler
install:
- bundle install --jobs=3 --retry=3
script:
- bundle exec rspec
- bundle exec rubocop
- bundle exec fasterer
notifications:
  email: false
  slack:
    secure: WN6Tc8kREPwVy7a+Pk1TpzKkzM8Hk++8Z8znAS51mkpvkv8g95HO9TysTZtQ+gv05L4l9V9tJsjVF2vCvJgrWQ84ilhpgBG62X+L2E/2SPB3TX0Hxh+VInCkmsg1h/FsnoZ1S9H4WjW6jbunCWl+ecytCJXNFvKtkmsbUAIVZY2jji6oKacsQZMeL+BvsKAnny7/1JJ3sSEuGZ4LXeQ1TL+mI74awmeJIuGWJfwNH6fW/z6sN4f/25ZNtiLEMZ+0rzzE7mO4k3GBv+tPPwqL1547/2KTEwHCSmPDHjpmzdA0yQ/razrA4n/Iqb5vS0ZCS6WYg6udiAh5aWwUg+g4VAzMegTqw0kGWpnTHNTuMzRGh1uKTXF5MH4T+a1FGOxnrFkZUZhCJPa2+NTbuHHxl6pycFxA+D7sGvEwaEbRgJ26y0IGk9ZnhJAhmtEddsCsdcPE4pb+10+ppbOZI1fW56UT3/f6l75Zj2QclmE2EjEi4+MqgLX8FJvT5iHhsBH7/MFNlOGftH/l2iiRFu9MmFC/BroAOF541DSP/n/Eocu7f2tiHV3Km9beHOWwYLL7nGhPhp2XlzaYA2eTQtzF3foswL440OO0PMfmmT2AbjK8uagvPPQkPFv40L40KLOnsKo+/tli8IjSqWDdwKrR69X0EmAflpu8UBzez8pCe9A=
